server:
  port: 8091

spring:
  profiles:
    active: mysql5x
  application:
    name: nb-consumer-movie

eureka:
  client:
    # 指定eureka server通信地址，注意/eureka/小尾巴不能少
    service-url:
      #defaultZone: http://localhost:8761/eureka/ 单机
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/  #eureka集群
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true