server:
  port: 8090

spring:
  application:
    name: nb-provider-user #指定注册到eureka server上的服务名称
  profiles:
    active: mysql8x



eureka:
  client:
    # 指定eureka server通信地址，注意/eureka/小尾巴不能少
    service-url:
      defaultZone: http://localhost:8092/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true