server:
  port: 8761


eureka:
  client:
    register-with-eureka: true #是否要注册到其他Eureka Server实例
    fetch-registry: true #是否要从其他Eureka Server实例获取数据
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: nb-discovery-eureka

